### ISSUE TITLE
barnumbers and change of meter

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#101]
I admit it is an exotic case. But It stems from a real piece of music.

```
X:3064
F:3064_3064barnumberandmeter
T:barnumber-and-meter
C:
S:
M:4/8 6/8=8/8
L:1/4
Q:1/4=80
K:C
%
%
%%score 1
%
V:1 clef=treble name="Sopran" snm="S"
C2 | C4 | C2 :| C2 | C/C/C/C/ |:[M:6/8][P:M:6/8]] C/C/ | C3/ C3/ | CC :| C | C3|
%
W:Expected Results
W:
W:Every visible bar has a consecutive number
W:
W:Note that the meter-Sybmol might lead to a missing bar number
W:as abc2svg does not consider the bar as full.
%
%
```

Yields

![screenshot_1188](https://user-images.githubusercontent.com/2022976/40376345-64fa054c-5dee-11e8-9329-4b28abaea71e.jpg)

There is a deviation between barnumbers in harp preview and in tune preview. Tune previewe does not number the bar between 3 and 4. I think it comes from the fact that abc2svg does not number incomplete bars. 

I admit, that In the given case with a meter within a measure, it is not clear, when the measure is considered to be completed.

Completion could be made according

* on the shortest meter (in this case 6/8) as the M: header specifies that 3/4 and 6/8 might occur
* the the active meter at the end of the measure

Alternatively, abc2svg could always add a bar number on relevant bars. It is difficult to define what is "relevant". In Zupfnoter, I consider all bars as relevant except repetition start repetition end which is not on beat 0.

you also see the count notes in the harp preview. The approach there is:

* before the meter I count as 4/4
* after the meter I count according to 6/8. In this case the two notes after the meter, count as 5, 6. In order to achieve this, I determine a "virtual measure start point" based on wmeasure of the meter for 6/8.

**Comment by moinejf** [comment]
I don't agree. There is a problem because the tune is not correctly written.   
There is
```
C2 | C4 | C2 :| C2 | C/C/C/C/ |:[M:6/8][P:M:6/8]] C/C/ | C3/ C3/ | CC :| C | C3|
```
while it should be:
```
C2 | C4 | C2 :| C2 | [M:6/8]C/C/C/C/ |:[P:M:6/8]] C/C/ | C3/ C3/ | CC :| C | C3|
```

**Comment by bwl21** [comment]
I see, in this case it is solution. I admit in measure meter changes are complex. OTH I am not sure, if it can always be avoided. Otherwise, we could even raise a warning for ma meter change which is not close to a measure bar.

As the original tune is copyrighted, i send it to you by PM, just for information.

**Comment by moinejf** [comment]
I did not see it before, there is an invisible bar in:
```
|:[M:6/8][P:M:6/8]] C/C/ |
```
(the double ']]')

Otherwise, the measure problem in the original tune (starting measure 16 - I replaced the notes by 'c'):
```
[M:3/4] cc cc c2  :] [M:4/4] z ccc  | c2 cc c2 c2 |
```
disappears with a normal/standard measure setting:
```
[M:3/4] cc cc c2  :] [M:2/4] z ccc  | [M:4/4] c2 cc c2 c2 |
```
(the measure 18 is on M:4/4)

**Comment by bwl21** [comment]
I see, so the approach is to specify meters such that the measures are filled properly (as you did with [M:2/4]. Now I am convinced that changing meter within a measure. 

Thanks.

I will implement a warning in my app for this case.
