### ISSUE TITLE
Request: tojson should provide Time for Meter symbols

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#102]
Hi

While converting abc2svg model provided by to_json, I need a time property for the meter symbols (type:6) It should be the time of the next playable symbol (rest or note ...).

Would this be possible?

Background see #101

I am computing count hints. I also suppress bars in case there is a repetition starting/ending within a measure. Now I have a case where the repetition starts within a measure. At the same time the user changes meter.  In this case I have to determine a "virtual measure start point in time" for the new meter. I do this by subracting wmeasure from the time of the next bar. To find the next bar symbol I need the time of the meter symbol. As of now I take it from the most recent note/rest + duration.

**Comment by moinejf** [comment]
Well, as told in the previous issue, there cannot be a measure change when the previous measure is not complete (music nonsense).   
But, anyway, there is a time property in all symbols.

**Comment by bwl21** [comment]
sorry, I did not see it before. Now I found it.
