### ISSUE TITLE
grid2 only works the first time

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#108]
When I take the example from the documentation in edit-1.xhtml

```
%abc-2.2
X:1
T:Lullaby of birdland
C:George Shearing (1919 - 2011)
M:C
L:1/4
%%score 1 2
K:Gm
V:1,2
"Gm6"d/d/c/B/"E7b"AG|"A7b9"=EG/^F/-"D7b9"F2| "Gm6"DA/G/-"E7b"G2|"Cm7"Ed/c/-"F9"c2|
"Bb7"f/f/e/d/"Gm7"cB|"Cm7"G/d/c/^F/- "F7b9"F/d/c/=F/-|\
 "Bb7"F2z/c/B/E/-|"Eb9"E/B/A/D/-"D7"D2|
V:1
%%grid2 1
w:Lu-lla-by of bird-land that's what I_ al-ways hear* when you sigh;_
+:Ne-ver in my word land could there be ways* to re-veal_ in a phrase* how I feel._
```

Initially it works fine, but when I remove %%grid2 1 and bring it back, the no chord symbols show up in voice 1

![screenshot_1197](https://user-images.githubusercontent.com/2022976/40471463-0ccc1924-5f37-11e8-999e-ee074b9f5735.jpg)

the same happens with %%voicecombine. When I change the code in edit-1.xhtml, then all combinations look the same

## other cases

* it also happens with %%ambitus. in the second run there is only a small line

    ![screenshot_1198](https://user-images.githubusercontent.com/2022976/40472158-ea6cda38-5f38-11e8-9907-16165737675f.jpg)

* percmap (using the example from https://wim.vree.org/js2/tabDrumDoc.html has the same problem. In addition to this in my app I get the message "no definition of square"

* I also observe the same problem with diagram but only in my app, not in edit-1.xhtml.

**Comment by bwl21** [comment]
To be honest, I feared, that it could a problem that modules depending on abc-code (processed by a particular instance) change the Class and not the instance of the Abc object. But without a clear understanding, I did not want to raise this issue, when we discussed #98. 

I tried the cases above with abc2svg-1.17.2-8-g67e6314 (2018-05-25)

**Comment by moinejf** [comment]
You are right. The problem should be fixed.
