### ISSUE TITLE
A couple display issues with %%grid2

### ISSUE THREAD

**Issue by chrisfargen** [moinejf/abc2svg#122]
I've been using `%%grid2` for lead sheets, and the results look awesome. However, there are two features I am missing.

First, it would be nice to have an option to remove ties. I understand why it might make sense to include them in some instances, but I have never before encountered them, and they can be a bit distracting.

![85930816-58ec4480-b88d-11ea-912f-1be339e860eb](https://user-images.githubusercontent.com/2993720/87257267-b70d5000-c467-11ea-8fcb-a7e2d8dde1ce.png)

```
X: 001
T: After You've Gone
C: Creamer, Layton, 1918
M:
L: 1/4
R: swing
Q: 220
%%staffsep 15
%%scale 1.2
%%equalbars 1
%%notespacingfactor 2
%%partsbox 1
K:Cmaj
V:1 % (needed after the first K:)
%%grid2 1
%
P: A
|"C" E G A B- | B4 | "C-" z A B A | B A3 |
|"G" B, D E F- | F4 | "E7" z E F E | F E3 |
|"A7" E B2 B- | B4 | "D7" E A2 A- | A4 |
|"G" z D E D | F D E D | "G7" G B,2 D- | D4 ||
P: B
|"C" E G A B- | B4 | "C-" z A B A | B A3 |
|"G" B, D E F- | F4 | "E7" z E F E | F E3 |
|"A-" c4| "E7" B4 | "A-" A ^D E B- | "C-6" B2 A2 |
|"G" z ^A B G | "B7" A ^G A F | "E-7" =G ^A, B, F- | "A7" F2 E2 |
|"G" D E G B- | "E7" B4 | "A-7" z C D E | "D7" A2 B2 |
|"G" B G3- | G4- | "G7" G4- | G4 |]
```

Secondly, I've noticed that the chord symbols do not always line up vertically. I've tried various fixes, such as using `%%notespacingfactor 2`, but I've had no luck so far. Furthermore, I can't figure out the logic by which some symbols are shifted to the right. See above (last measure). See below (misalignment between second line and third line).

![out](https://user-images.githubusercontent.com/2993720/87257585-208e5e00-c46a-11ea-840c-01ca90ca7a1d.png)

```
%%titleformat X+T R- Q- C1
%%partsfont Times 14 box
%%gchordfont Times 20
%
%%pagewidth 8.5in
%%pageheight 11in
%%titlespace 0
%%topmargin 0.5in
%%leftmargin 1.5in
%%rightmargin 1.5in
%%scale 1
X: 
T: It's a Lonesome Feeling
C: Billy Henson
M:
L: 1/4
R: Bluegrass
Q: 220
%%staffsep 15
%%equalbars 1
%%partsbox 1
%%notespacingfactor 2
K:Gmaj
V:1 % (needed after the first K:)
%%grid2 1
%%scale 0.8
%
P: Verse/Chorus
|"G" z4  | z4     | "G" z4 | z4 |
|"G" z4  | "F" z4 | "C" z4 | z4 |
|"Am" z4 | z4     | "G" z4 | z4 |
|"Am" z4 | "C" z4 | "G" z4 | z4 ||
P: Outro
|"Am" z4 | "C" z4 | "G" z4 | z4 |]
```

Any help appreciated.

Also, this is a great project! Thanks for your work.

**Comment by moinejf** [comment]
Both problems should be fixed in the fossil repository and on my site.
Thanks for the report.
