### ISSUE TITLE
Feature request: Support for tab clef?

### ISSUE THREAD

**Issue by chrisfargen** [moinejf/abc2svg#123]
![out](https://user-images.githubusercontent.com/2993720/87572669-e4414480-c699-11ea-8a3f-af7b4e491be8.png)

I have been rendering guitar tab using abc2xml -> xml2abc -> abc2svg as discussed [here](https://wim.vree.org/js2/tabDrumDoc.html). The ABC starts out very readable.

```
X:1
%%score [ 1 | 2 ]
K:Cm
%
% STANDARD NOTATION
V:1 clef=bass-8
C,3 E,3 G,A,| G,3 F,3 G,D, |
%
% BASS GUITAR TAB
V:2 clef=tab octave=-1 strings=E1,A1,D2,G2 nostems
C,3 E,3 G,A,| G,3 F,3 !2!G,D, |
```

I'm very happy with the final product, but the process is a bit cumbersome, requiring two intermediary utilities and resulting in the ABC becoming significantly less readable.

Tab is a common form of notation in contemporary music learning resources. It can be easily specified in ABC with only minor modifications to the standard (e.g., overriding a computed string/fret using a special decoration). And the `clef=tab` option would seem to preclude the possibility of breaking existing ABC.

Therefore, I wonder if there are other obstacles that prevent tablature from being natively supported?

**Comment by chrisfargen** [comment]
I understand there are probably many more priority items in the development of this project, but I wonder--would it make sense to support tab at some point down the line? Would this require a great deal more logic than other supported output notations like jianpu and clairnote?

**Comment by moinejf** [comment]
I had no request yet about tab support in abc2svg. Anyway, many things are doable.
Willem's syntax is just a shortcut for defining simple tabs. This syntax seems clear enough, but I don't think I can keep it. First, it does not follow the way I add extra features (I need the presence of a pseudo-comment to load the module associated to the feature). Then, I don't like the string list that does not contain standard ABC pitches.
So, instead of adding some specific code to the core of abc2svg, I'd rather go to a front-end. I will need some time to define it...

**Comment by moinejf** [comment]
I started to implement Willem's syntax.
The script is called `wvtab.js`. I uploaded it to my site (http://moinejf.free.fr/js/).
It must be inserted before the ABC files with the command line scripts, or included by <script> in HTML+ABC files.
The options `diafret` and `capo` do not work yet, nor do chords with notes on a same string.

**Comment by chrisfargen** [comment]
Jef, thanks for implementing this! I can tell it's going to be very useful.

So far, each time I try it, I'm getting an error. Examples below.

----

### Bass tab

- abc2xml -> xml2abc -> abc2svg:

![out](https://user-images.githubusercontent.com/2993720/87572669-e4414480-c699-11ea-8a3f-af7b4e491be8.png)

- abc2svg + wvtab.js:

![out-wvtab-bass](https://user-images.githubusercontent.com/2993720/88459917-94ffce80-ce66-11ea-9b42-e95311c4a288.png)

- ABC:

```
X:1
%%score [ 1 | 2 ]
K:Cm
%
% STANDARD NOTATION
V:1 clef=bass-8
C,3 E,3 G,A,| G,3 F,3 G,D, |
%
% BASS GUITAR TAB
V:2 clef=tab octave=-1 strings=E1,A1,D2,G2 nostems
C,3 E,3 G,A,| G,3 F,3 !2!G,D, |
```

----

### Ukulele tab

- abc2xml -> xml2abc -> abc2svg:

![out-good-ukulele](https://user-images.githubusercontent.com/2993720/88459943-c082b900-ce66-11ea-9e15-ba729ebb86a8.png)

- abc2svg + wvtab.js:

![out-wvtab-ukulele](https://user-images.githubusercontent.com/2993720/88459946-c5e00380-ce66-11ea-9470-335ec323042f.png)

- ABC:

```
X:2
%%score [ 1 | 2 ]
K:C
L:1/4
%
% STANDARD NOTATION
V:1
C C D || E2 E2 | z E D E | C2 C2 | 
%
% UKULELE TAB
V:2 clef=tab stafflines=4 strings=G4,C4,E4,A4 nostems 
C C D || E2 E2 | z E D E | C2 C2 | 
w: You are my | sun-shine, my on-ly | sun-shine
```

----

### Guitar tab

- abc2xml -> xml2abc -> abc2svg:

![out-good-guitar](https://user-images.githubusercontent.com/2993720/88459956-d7291000-ce66-11ea-9e23-673126a245ef.png)

- abc2svg + wvtab.js:

![out-wvtab-guitar](https://user-images.githubusercontent.com/2993720/88459959-de501e00-ce66-11ea-98e2-510a54e3349e.png)

- ABC:

```
X:3
%%score [ 1 | 2 ]
K:C
L:1/4
%
% STANDARD NOTATION
V:1 treble transpose=-12
E, A, D G | B e z2 | e B G D | A, E, z2 ||
%
% GUITAR TAB
V:2 clef=tab octave=-1 nostems
E, A, D G | B e z2 | e B G D | A, E, z2 ||
```

----

Any guidance appreciated. Thanks for working on this feature.

**Comment by chrisfargen** [comment]
I am using Abc2svg-1.20.11 downloaded via sourceforge.net and running web editor locally. Only change to editor is inclusion of the following line:

```
...
<script src="./abc2svg_files/err-it.js" type="text/javascript" />
<!-- Added wvtab.js -->
<script src="./abc2svg_files/wvtab.js" type="text/javascript" />
</head>
...
```

**Comment by moinejf** [comment]
About the tunes 2 and 3, the length unit definition L: is not at the right place. It is after the first K:, so, it applies to the first voice (V:1) only. The second voice, V:2, has the default L:1/8.
Otherwise, about the bad pitches in the tablature, I don't remember about any bug in the abc2svg core. Anyway, I uploaded a newer version (abc2svg-1.js version 1.20.12-c556925ce1 date 2020-07-20) to my site. Can you try it?

**Comment by chrisfargen** [comment]
> About the tunes 2 and 3, the length unit definition L: is not at the right place.

Ahhh I see that now. That fixed it.

> Anyway, I uploaded a newer version (abc2svg-1.js version 1.20.12-c556925ce1 date 2020-07-20) to my site. Can you try it?

New version fixes my issue with the first tune. Bravo!
