### ISSUE TITLE
Q: What is a "block" symbol

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#13]
I stumbled over a block symbol in the model but do not have a handler for it. What is it, and now shall I treat it (if not simply ignore)

**Comment by moinejf** [comment]
Block symbols contains formatting commands found inside tune bodies as T:, %%text or %%leftmargin.
When found outside tune bodies, these commands are immediately executed.
When inside bodies, they are executed when encountered during the generation.

**Comment by bwl21** [comment]
I see, I can simply ignore them for zupfnoter. Thanks.
