### ISSUE TITLE
overlay voices have not bar symbols

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#14]
I see that overlay voices to not have bar symbols. It appears reasonable since the regular notation has such things in the main voice. But for tableharps I need to handle overlay voices as regular voice with all features.  

Would it be easy for you to add this information? 
Would it be sufficient, to remove all bars from overlay voices and duplicate the bars from voice 0 into the overlay voice according to the time? Then I can do it on my side.

May testcase was
```
C4|(3DDD (3DDD &  F  (3GGG G - | D4 & G GGG | E4 | E4 & d4 |
```
In this case the overlay voice indeed does not have bars in the ABC-code.

**Comment by moinejf** [comment]
IIRC, I already answered such a question.
Overlay voices may start and stop on any symbol:

    c/d/(&e/f/ & c &) [eg]2 |

    cd (& ef | g2 & c2 | ed &) c2 |

The sequence

    c4 | g4 & G4 | c4 |

may be written as

    c4 | (& g4 & G4 &) | c4 |

Both sequences give the same result and have a same model.

**Comment by bwl21** [comment]
This is true, but the model has no bar symbols since ABC-Notes have no bars in the overlay voices.

As abc does not allow to put the overlay voice in an extra stave, you do not need bars in the model.  As zupfnoter places each voice in an extra stave, I need the bars in the model. I think I fix it in my transformation and close the issue.
