### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by zepedrorocha** [moinejf/abc2svg#15]
We tried upgrading from 1.12.10 to a recent build (8e76f3b) - and we started having these errors.
This happens on Electron+Webpack+Angular. A smaller test app with Webpack+Angular works fine.

````
index.html:21 Uncaught ReferenceError: exports is not defined
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (scripts.bundle.js:63), <anonymous>:21:253829)
    at eval (<anonymous>)
    at webpackJsonp.../../../../script-loader/addScript.js.module.exports (scripts.bundle.js:63)
    at Object.../../../../script-loader/index.js!../../../../../src/vendor/abc2svg/abc2svg-1.js (scripts.bundle.js:72)
    at __webpack_require__ (inline.bundle.js:55)
    at Object.13 (scripts.bundle.js:127)
    at __webpack_require__ (inline.bundle.js:55)
    at webpackJsonpCallback (inline.bundle.js:26)
    at scripts.bundle.js:1
````

We will try to isolate this, but if you have any ideas or suggestions, please let us know.
Thx

**Comment by moinejf** [comment]
May you try this patch?
```
--- a/core/tail.js
+++ b/core/tail.js
@@ -29,7 +29,7 @@
 }      // end of Abc()
 
 // nodejs
-if (typeof module == 'object') {
+if (typeof module == 'object' && typeof exports == 'object') {
        exports.abc2svg = abc2svg;
        exports.Abc = Abc
 }
```

**Comment by zepedrorocha** [comment]
Hello again, that patch indeed fix the problem. The issue here is with electron + your code and how I add your script to the app.

If I use <script> tag to add your code, and since I am running inside of an electron app (nodejs), that condition in the end will be true and there's no "exports" in the web and a error will appear. Your patch fixes that.
This is me trying to isolate the problem:
https://drive.google.com/open?id=0ByeGxAHc8Lj8TEpfR2dSTUpfMkE

The other reasonable option that I have available (since I am running inside of a node env) is the use of require(), which I believe your code is prepared to run in node **only** via command-line-interface.
Here I was expecting the same js behaviour but had to **hack**-around the problem:
https://drive.google.com/open?id=0ByeGxAHc8Lj8aGhZYlFSbUdjSzA

**Comment by zepedrorocha** [comment]
Hello again. Since you didn't close this ticket yet I am also going to address the same problem happens in the play-1.js file

![image](https://user-images.githubusercontent.com/5140092/29999106-ed92533e-9033-11e7-84b1-9535b5dd078a.png)

Thanks.
