### ISSUE TITLE
How to represent "sf" (subito forte) in ABC?

### ISSUE THREAD

**Issue by joaocc** [moinejf/abc2svg#16]
We have looked in the standard (http://abcnotation.com/wiki/abc:standard:v2.2) and it seems not to exist.
If not, can abc2svg render the correct dynamics even if not in the standard?
thx

**Comment by moinejf** [comment]
Yes. You may define a decoration as:

    %%deco sf 6 pf 18 2 10 @-4,0sf

**Comment by joaocc** [comment]
Thx!
