### ISSUE TITLE
Some slurs overlap with notes

### ISSUE THREAD

**Issue by Badim150** [moinejf/abc2svg#17]
Sometimes when the slur is big and/or a note is high above the staff, the slur overlaps the notes:

![image](https://user-images.githubusercontent.com/8185565/29381891-b5089344-82c2-11e7-9e4f-ab36834a05a1.png)

```
X:1
Z:Copyright ©
%%scale 0.83
%%pagewidth 21.00cm
%%leftmargin 1.27cm
%%rightmargin 1.27cm
L:1/8
M:18/8
I:linebreak $
K:C
V:1
 (C_EG c_eg c'_e'g' c''g'e' c'ge cGE) |$ 
```

**Comment by moinejf** [comment]
The slur height may be adjusted:

    %%slurheight 1.4    % default value 1

**Comment by Badim150** [comment]
Thank you!
