### ISSUE TITLE
I:transpose=2 - error is not user friendlcy

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#18]
I know, this is a difficult thing, nevertheless, i report it and leave it up to you if you improve it.

using 1.13.7; If I enter

```
I:transpose=2
```
I get the message

`Cannot read property 'uscale' of null``

Of course this is a syntactical error, maybe it is possible to report it as such.

**Comment by moinejf** [comment]
Fixed by commit 0a5ac758c24a984d85a5bd4e82e12aa61588a8d7
Thanks

**Comment by bwl21** [comment]
I see, I:transpose also accepts intervals

so `I:transpose =2` yields an error since `=` is considered as accidental and `2` then should be a note.
