### ISSUE TITLE
Dynamics "sfz" is not recognized even though it is part of the "standard"

### ISSUE THREAD

**Issue by joaocc** [moinejf/abc2svg#19]
This one is similar to #16, but "sfz" is part of the standard.
Any particular reason for this not to be supported?
Do you have plans to add it, or it's better if we use a similar solution to that on #16?
Thx

**Comment by moinejf** [comment]
Fixed by commit 2e5cbb2bfd02d40fe4149290245b84da7d6a3cfd
Thanks
