### ISSUE TITLE
Make abc2svg available as npm package

### ISSUE THREAD

**Issue by joaocc** [moinejf/abc2svg#2]
The name says it all :)
It's easier to control import as npm package than as direct git import.

Ideally (from our p.o.v.) it could allow use it as an Angular 4 components. If not, then we can always create an angular wrapper package later on.

Thanks!

**Comment by Ralex86** [comment]
I totally agree with jaocc. I also think it would be a good idea to provide abc2svg as an npm package. It would be easier for me to use it with React. Abcjs does provide an npm install by the way. But we don't want to use Abcjs as it has tons of ugly dependencies such as Raphael and Jquery.....

**Comment by moinejf** [comment]
Done.

**Comment by joaocc** [comment]
Great! We will update our tester ( https://github.com/highskillz/ng-xml2abc2svg ) to make use of it, already with the new version. Thank you

**Comment by moinejf** [comment]
npm package abc2svg created. Last commit: f2a72a1401e387d089f377fd632d01f5332481ec
