### ISSUE TITLE
Octave clefs do not work with accidentials

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#3]
The following code

```abc
X:1
F:octave_clefs
T:Octave clefs
M:4/4
L:1/4
Q:1/4=120
K:C
%
%%score 1
%
V:1 clef=treble-8 octave=1 name="Sopran" snm="S"
C ^C D ^D E F ^F G ^G A ^A B 
```
Does not yield the correct midi values in the json. it does not respect the accidentals.
It yields 
```
              "midi": 60
              "midi": 60
              "midi": 62
              "midi": 62
              "midi": 64
              "midi": 65
              "midi": 65
              "midi": 67
              "midi": 67
              "midi": 69
              "midi": 69
              "midi": 71
```
Without the Octave clef I get

              "midi": 72
              "midi": 73
              "midi": 74
              "midi": 75
              "midi": 76
              "midi": 77
              "midi": 78
              "midi": 79
              "midi": 80
              "midi": 81
              "midi": 82
              "midi": 83

I Wanted to try it on http://moinejf.free.fr/js/edit-1.xhtml to see, how it plays, but the player there crashes with

![screenshot_895](https://user-images.githubusercontent.com/2022976/29017630-ea24d3de-7b57-11e7-95bc-357519750910.jpg)

**Comment by moinejf** [comment]
Should be fixed.
Thanks.

**Comment by bwl21** [comment]
Yes, it works with that testcase.
