### ISSUE TITLE
play.js: Cannot read property 'time' of undefined

### ISSUE THREAD

**Issue by zepedrorocha** [moinejf/abc2svg#30]
In the current version, v1.14.1 the play functionality doesn't work well with repeats (In the previous version this was working fine)

How to reproduce: 
1- copy the following abcnotation in http://moinejf.free.fr/js/edit-1.xhtml
```javascript
X:1
%%measurenb 0
%%slurheight 1.4
%%scale 0.83
L:1/16
M:4/4
I:linebreak $
K:A
V:1
|: (ABcd edcB ABcd edcB | ABcd edcB ABcd edcB) :| %2
```
2- Try to hit 'play'
![image](https://user-images.githubusercontent.com/5140092/30605357-b442a496-9d65-11e7-8bad-5c036a78fd1f.png)

**Comment by zepedrorocha** [comment]
In this example the repeat won't crash but will not be played correctly;
```text
X:1
%%measurenb 0
%%slurheight 1.4
%%scale 0.83
L:1/8
M:2/4
I:linebreak $
K:E
V:1 treble nm=""
V:1
"^(Liebesgruss.)""^Andantino" z4 | z4 |:"_dolce"!p! (vg2 Bg) |"_legatiss." (fe)vd!<(!(ue | %4
!<)! .a2) !tenuto!va2 |!>(! (ua2!>)! B) z | (g2 ^Bg) | (fe)d!<(!(e |!<)! f2) !tenuto!f2 | %9
!>(! (f3!>)! ^^f) |$ (g2 B"_cresc."g) | (fe)d!<(!(e |!<)! .c'2) !>!c'2 | %13
!>(! (c'2 !tenuto!b!tenuto!a)!>)! |!p! (g2 !tenuto!f!tenuto!e) |!<(!"_dolciss."{/e} (c2!<)! d2) |1 %16
!<(! e4- |!<)! e2 B2 :|2!>(!"_dim." e4- | e4!>)! ||$!pp!{/e} ((u=g2 f)!tenuto!e) | %21
 ((=c2 =d)!tenuto!e) | ((f2 e)!tenuto!=d) | (B2 =c"_poco cresc."=d) | (e2 f=g) | (a2 b=c') | %26
!<(! %3|]
```
The first note in the repeat will be skipped and then in the end will misplay the piece. 
Set follow to true for easier track.

Thanks

**Comment by zepedrorocha** [comment]
Hello again, thanks for the commit. The "Cannot read property 'time' of undefined" is resolved but the second example I gave the repeat doesn't quite work properly yet.

**Comment by moinejf** [comment]
Sorry, but I do not hear any problem about repeat with your tune.
Maybe your are talking about the accaciatura. It is not coded yet.

**Comment by zepedrorocha** [comment]
> Sorry, but I do not hear any problem about repeat with your tune.
Maybe your are talking about the accaciatura. It is not coded yet.

yes. [video](https://streamable.com/82mgb)

Thanks.

**Comment by moinejf** [comment]
The same I get. What do you think is wrong?

**Comment by zepedrorocha** [comment]
Hey sorry about my misunderstanding . A college already explained the behavior is correct due to the presence of the first and second repeat signs.

Thanks.
