### ISSUE TITLE
Q: effect of accidentals across voices

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#33]
In an earlier discussion we found that accidentals of one voice effects the others if they are in the same measure and the same octave.

Below I illustrate the problem with abc and Zupfnoter output which visualizes the pitch provided by midi.js. The test also works on http://moinejf.free.fr/js/edit-1.xhtml but only audible.

The pitch of the one note in V:2 collides with the pitch of beat 5 in V:1. So the result is a D#/Eb instead of an E.

First I thought it is a leftover of #3, but I think it is that the accidental of V:2 affects V1 as it is in the same octave.

This leads to the question: does the "same octave" refer to the noted or to the played octave.
Not sure if this is a bug, but in any case, I think it is an interesting case and worth to be documented.

```
X:1
F:octave_clefs
T:Octave clefs
M:12/16
L:1/16
Q:1/4=60
K:C
%
%%score 1 2
%
V:1 clef=treble-8 octave=1 name="Sopran" snm="S"
C ^C D ^D  E  F ^F G ^G A ^A B  |
V:2 treble
_E12   |
```

yields

![screenshot_967](https://user-images.githubusercontent.com/2022976/31307746-8e0678e4-ab6a-11e7-8d2b-c7440916e37c.jpg)

The pitch of the one note in V:2 collides with the pitch of beat 5 in V:1

If I move V:2  to another octave such that I do not have the collision, then everything is fine.

![screenshot_968](https://user-images.githubusercontent.com/2022976/31307751-aef488c0-ab6a-11e7-8515-5ab9ffab7445.jpg)

**Comment by moinejf** [comment]
This was a lack: the accidentals were treated globally.
The commit 1e156fdcd34968046c29df32a88a02144ff3fbbc should fix the problem.

**Comment by bwl21** [comment]
Tested with commit 5d06fd4 - problem fixed. Thanks,

![screenshot_981](https://user-images.githubusercontent.com/2022976/31660951-60790d20-b339-11e7-8a67-10b0d051c41a.jpg)
