### ISSUE TITLE
calling function to render abc

### ISSUE THREAD

**Issue by jisike** [moinejf/abc2svg#37]
is there a way to call a function in abc2svg to render abc that is stored in a variable? it looks like it's mostly designed to be used as an editor. but im manipulating computationally as opposed to manually in a textarea.

**Comment by moinejf** [comment]
I don't see what you want to do.
ABC cannot be stored in a variable. The internal representation of the music is a complex data structure.
What do you mean by 'render'? If it is displaying the music, actually, there is no way to directly inject the music as a data structure into the SVG generator of abc2svg. You will have to use the module toabc.js to translate the structure into ABC and then to inject ABC into the abc2svg core.
Anyway, building manually the structure is more complex than writing ABC...

**Comment by jisike** [comment]
I dont know how we keep misunderstanding each other but I found my answer here:

```
abc2svg = new Abc(user);
abc2svg.tosvg('abc2svg', abc);
```
