### ISSUE TITLE
decoding  note font/symbol

### ISSUE THREAD

**Issue by jisike** [moinejf/abc2svg#41]
How can I decode the  font/symbol inserted in <text></text> for the notes. I need convert it to a value which can be used to compare whether the text is a note, dot or an accidental.

**Comment by jisike** [comment]
Just found I can use charcodeat

**Comment by moinejf** [comment]
The music characters used in abc2svg are defined in the table tgls in svg.js.
Their encoding follow SMUFL's one (https://www.smufl.org/).
