### ISSUE TITLE
play.js: onend fires too early

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#43]
I observe that `onend` fires too early. I assume, it fires when the last note is scheduled. In my expectation, it should fire when the last note is turned off.

you can reproduce it with 

```
X:1
K:C
E4 F4
```
If you play this in http://moinejf.free.fr/js/edit-1.xhtml, you can see that play button toggles immediately after playing the E4.

You can also observe it by setting a breakpoint in the browser, you can see that after calling `endpoint`, there are more calls to `notehighlight`

![screenshot_1007](https://user-images.githubusercontent.com/2022976/32317761-309befb8-bfb5-11e7-8f54-7a0c3fcd34e2.jpg)

**Comment by moinejf** [comment]
The play events are (actually) submitted each 3 seconds for 3 seconds.
This submission loop is started 300 ms before the end of playing of the previous sequence.
Then, on playing end, the callback function onend() is called 300ms before the real end of playing.
As you may see, even if the button 'play/stop' is immediately set back to 'play', highlighting the selection and enabling more playing are done 2 seconds later.

Indeed, if this software would be a fast compiled program, realtime could be handled in an efficient way, but, as javascript is slow, the less instructions there are and the best the realtime is working.

**Comment by bwl21** [comment]
Verified with 8605f7d. Works fine. Thanks.

I investigated the code, and there is might be a small risk that 'onend' fires before 'on_note'. They both are scheduled with onTimeout and the same time. But as on_note is scheduled first, I think it also fires first. So I close this issue.
