### ISSUE TITLE
nested repetitions do not play properly

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#45]
The following testcase indicates that nested repeats do not play properly. 

On the other hand, nested repetitions are virtually never notated that way, because it is virtually 100% likely a human musician won't be be able to follow the intended roadmap. 

So If you wand to close this as "Wontfix" it is ok.

```
X:1
L:1/8
F:3047_nested-repetion-play
M:4/8
K:C octave=-1 treble
cdef | gabc' :|: defg |1 abc'd' :|2 GABc |] defg :|
%
W:Should play measures in following order
W:
W:a: 1 2  -  1 2  -  3 4(1) -  3 5(2) -  6 
W:b: 1 2  -  1 2  -  3 4(1) -  3 5(2) -  6
W:
W:But the last repetiton  (b) starts on measure 3
```

![screenshot_1010](https://user-images.githubusercontent.com/2022976/32373802-58cb4f1a-c09b-11e7-9105-cade99617029.jpg)

Zupfnoter's output visualizes the flow

![screenshot_1011](https://user-images.githubusercontent.com/2022976/32373822-7b875e0e-c09b-11e7-8002-d0571e5ef755.jpg)

**Comment by bwl21** [comment]
Tried with commit 16cd573, Problem is still there. It can also be seen with Testcase 3022

**Comment by moinejf** [comment]
As it is said in the commit comment, 'This just prevents the loop'.
Nested repeats should not exist (see the bottom of page https://musescore.org/en/node/18974), so, I will not treat this case.
Correct playing with abc2svg asks for some development: handle the repeat numbers, Da Capo, Da Segno, Coda and the ABC parts (P:). Also a 'dorepeat' command must be added to force the repeats when played one more time.

**Comment by bwl21** [comment]
Ok, I accept that. So we close this with a WONTFIX
