### ISSUE TITLE
blues with accidentals

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#46]
I admit to have a strange issue. I imported a piece from somewhere else which has Key changes and transpositions in one voice only.

The following abc code is an extract of W.C.Handy's "St.Louis blues". As I integrated play-1.js to Zupfnoter and provided to loaders for the player (one from ABC-Model, one from Zupfnoter-Model which gets its pitches by midi.js AbcMIDI), I expected both to sound the same. But (according to murphy's law - surprise, surprise :-) they don't!

![screenshot_1015](https://user-images.githubusercontent.com/2022976/32387124-be157b34-c0c3-11e7-8ccd-e867ba64b79c.jpg)

When I remove the I:transpose -2 in V:1, then V2 renders correctly.

```
X:348
F:348_abcsvg-issue-46
T:46 Blues midi.js
%%scale 0.83
%%pagewidth 21.01cm
%%leftmargin 1.00cm
%%rightmargin 1.00cm
%%score 1 4
L:1/8
Q:1/4=140
M:4/4
I:linebreak $
K:C
V:1 treble transpose=-2 nm="Sopransaxofon" snm="S. sax."
V:4 bas nm="Double Bass" snm="Db."
L:1/4
V:1 
I:transpose -2
|: [K:A]"A7" cecA- A4 | %18
"D7" z =F^FA =c2 BA|
%V
V:4
|: [K:G] G, =F, "^!^ this should be E not D#" E, D, | C, D, ^D, "^!^ this should be E not D#"E, |
```

Zupfnoter with midi.js in commit bf816c7 yields the correct notes vor V:4

![screenshot_1014](https://user-images.githubusercontent.com/2022976/32386797-ad8f879c-c0c2-11e7-8c9d-e519274c7ba8.jpg)

Zupfnoter with midi.js from commit 23f3bb5 yields wrong notes (note that commit 1e156fd was crashing)

![screenshot_1013](https://user-images.githubusercontent.com/2022976/32386678-4d510c98-c0c2-11e7-9a4a-c753b5f292e6.jpg)

It appears that we still have some trouble with accidentals. In the upper voice it also looks strange, that we have two neutrals caused by the key switch.

**Comment by bwl21** [comment]
some remarks:

1. I double checked with #33, but the testcase for #33 is still ok, so it must be something different.
2. Do we have a double maintenance problem between midi.js and play.js? Maybe it is worth to think of dropping ABCmidi and let ABCPlay.add do the job of setting the midi pitches.

**Comment by moinejf** [comment]
Bug found (lack in commit 1e156fd).
midi.js and play.js (toaudio.js) do not work the same: midi.js just sets the MIDI pitches voice per voice while toaudio.js generates the play events by increasing time and looping on the repeat sequences.

**Comment by bwl21** [comment]
I integrated commit 8605f7d in the feature branch of https://github.com/moinejf/abc2svg/pull/44
which I currently use for zupfnoter.

It works fine. Thanks for your immediate response and fix.

> while toaudio.js generates the play events by increasing time and looping on the repeat sequences.

Sure, but I thought that while doing this, it could also annotate the MIDI pitches. I was just an idea to simplify maintenance. On the other hand it might be better to separate these concerns
