### ISSUE TITLE
More blues with midi.js accidentals and ties

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#48]
similar to #46 there is one more thing where midi.js deviates from player js. I think play.js is right here.

Accidentials should survive the tie if the tie crosses a measure

```
X:3049
F:3049_abcsvg-issue-48
T:48 Blues with ties midi.js
%%score 1
L:1/4
Q:1/4=120
M:3/4
I:linebreak $
K:C
V:1 treble nm="Sheng, melody" snm="She."
V:1
   ^B A B - |$ "^!this should be C" B3 | ^F E F - | "^!This should be F#" F3 |]
```

![screenshot_1016](https://user-images.githubusercontent.com/2022976/32415547-b60d1374-c23b-11e7-8259-e92b1065b77c.jpg)

Yields in zupfnoter based on midi.js

![screenshot_1017](https://user-images.githubusercontent.com/2022976/32415551-d6760120-c23b-11e7-8569-5546503e11df.jpg)

But it sounds correct in http://moinejf.free.fr/js/edit-1.xhtml

**Comment by moinejf** [comment]
Should be fixed. Thanks.

**Comment by bwl21** [comment]
Tested it with eee5e5e and found it fixed. Thanks.

![screenshot_1023](https://user-images.githubusercontent.com/2022976/32555774-f35cfb2c-c49d-11e7-8283-ec283a1ebf09.jpg)
