### ISSUE TITLE
Crash with gchord.js

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#49]
The following code causes abc2svg to crash in line introduced by commit 0928c89

If you remove the % in line 18, it works fine.

```
X:3049  
F:3049_github_issue-49
T:https://github.com/moinejf/abc2svg/issues/49
%%score 1  4
L:1/8
Q:1/4=140
M:4/4
I:linebreak $
K:C
V:1 treble 
V:4 bas 
L:1/4
V:1
I:transpose -2
 z eec |:"Am"  Z |1 %7
"Am" Z | Z :|2 
%remove percent in next line - the crash disappears
%"Am" "x"e |]%29
%
V:4
z2 |:   %6
Z |1 Z | Z "^@@5":|2 
 z/ |] %29
```

in the following stackdump abc2svg-1 was created by ninja
```
Bug Cannot read property 'undefined' of undefinedTypeError: Cannot read property 'undefined' of undefined
    at draw_gchord (http://localhost:9292/assets/abc2svg-1.self.js?body=1:20139:19)
    at draw_deco_staff (http://localhost:9292/assets/abc2svg-1.self.js?body=1:1754:4)
    at draw_sym_near (http://localhost:9292/assets/abc2svg-1.self.js?body=1:5386:2)
    at output_music (http://localhost:9292/assets/abc2svg-1.self.js?body=1:12074:4)
    at generate (http://localhost:9292/assets/abc2svg-1.self.js?body=1:18197:2)
    at end_tune (http://localhost:9292/assets/abc2svg-1.self.js?body=1:7171:3)
    at Abc.tosvg (http://localhost:9292/assets/abc2svg-1.self.js?body=1:7224:5)
    at $Abc2Svg.$draw (http://localhost:9292/assets/opal-abc2svg.self.js?body=1:137:17)
    at $Controller.$render_tunepreview_callback (http://localhost:9292/assets/controller.self.js?body=1:537:35)
    at http://localhost:9292/assets/controller.self.js?body=1:601:43

io.self.js?body=1:140 
```

**Comment by moinejf** [comment]
I made a lot of changes in gchord.js and, actually, I have no problem with your tune.
May you get the last commits and check if this problem is fixed?

**Comment by bwl21** [comment]
The problem is still there in commit 432510d. It does not happen with 19c6c35, which is V15.0.

**Comment by bwl21** [comment]
I tried to furhter track down what causes the problem. In the following simpler example, I observe that the problem vanishes if 

1. I either remove the % in line with %29. If I then remove the "z" the problem reappears.
2. I remove the variant ending in line with "Z "^foo":|2"

In both cases the problem is, that "s.notes" as well as "s.nhd" is undefined. 

Hope that you can reproduce the issue.

```
X:3049  
F:3049_github_issue-49
T:https://github.com/moinejf/abc2svg/issues/49
%%score 1  2
L:1/8
Q:1/4=140
M:4/4
I:linebreak $
K:C
V:1 treble 
  Z :|
%remove percoent in next line to fix
%z |]%29
%
V:2
  Z "^foo":|2
 z |]
```
If you add another Bar at end of V1, it works, if you leave out the bar, then it crashes

**Comment by bwl21** [comment]
Update:

sorry, it was the same issue as we had  #35; my fault that I did not remember this.
The problem occurs as soon as I add a ``%%text`` at the end. I updated the testcase below.

It does not happen in 1.15.0




I tried to further track down what causes the problem. In the following simpler example, I observe that the problem vanishes if 

1. I either remove the % in line with %29. If I then remove the "z" the problem reappears.
2. I remove the variant ending in line with "Z "^foo":|2"

In both cases the problem is, that "s.notes" as well as "s.nhd" is undefined. 

Hope that you can reproduce the issue.

```
X:3049  
F:3049_github_issue-49
T:https://github.com/moinejf/abc2svg/issues/49
%%score 1  2
L:1/8
Q:1/4=140
M:4/4
I:linebreak $
K:C
V:1 treble 
  Z :|
%remove percoent in next line to fix
%z |]%29
%
V:2
  Z "^foo":|2
 z |]
%%text foo
```

**Comment by moinejf** [comment]
Sorry for I did not alert you sooner: removing I:linebreak is enough to show the problem.
I will upload the fix ASAP.

**Comment by bwl21** [comment]
removing I:linebreak did not change anything on my side.

How can I run edit-1.xhtml from the github repo such that I could investigate such problems independant of Zupfnoter?

**Comment by moinejf** [comment]
Indeed, removing I:linebreak does not change for you. But, for me, this added a new line at the end of the first voice.
For edit-1.xhtml use, just put your ABC code in the source area.
Otherwise, to know about the abc2svg core problems, use one of the batch scripts.

**Comment by bwl21** [comment]
I wanted to run edit-1.xhtml with a local webserver directly from my git clone. This would allow me to isolate problems coming from Zupfnoter integraton. But I will also try with the batch scripts. I even once ran the batch scripts through all of my abc files.

**Comment by moinejf** [comment]
You don't need a webserver. It you installed abc2svg and generated the *-1.* files in some directory, you may start your webbrowser with the URL:
   file:///path_to_the_abc2svg_source/edit-1.xhtml

**Comment by bwl21** [comment]
Here is another case with `%%text`

```
X:1
K:C
V:1
cde ::
V:2
cde |]
%%text foo
```

yields

![screenshot_1026](https://user-images.githubusercontent.com/2022976/32651408-421445cc-c601-11e7-9a92-1fe8b838783f.jpg)

with out the %%text in the last line, i get

![screenshot_1027](https://user-images.githubusercontent.com/2022976/32651430-4e354c2a-c601-11e7-9e18-d91c5b4e4793.jpg)

It is not a big problem but it is unexpected.

**Comment by moinejf** [comment]
This is normal:
- with %%text, a linebreak is added and the repeat :: is cut into :| in the first line, and |: in the second line. Then, after the %%text, the second line has only one bar, so, it is not printed.
- without %%text, the bars are displayed as indicated, and, as there is only one line, this one is shrinked to natural spacing.

**Comment by bwl21** [comment]
I have tested it with cc2a74a . it no longer crashes. Thanks for that.

I was still surprised to see the text between the two lines and not after the second line caused by V:2.

![screenshot_1030](https://user-images.githubusercontent.com/2022976/32690374-06500260-c6f6-11e7-9ecf-a543d74ffd7e.jpg)

I guess I somehow understand:

%%text is a symbol which es rendered after the current staff line is completed. The first voice (V:1) determines the breaks in the staff line.  Therefore after V:1 is finished, we see the line break in the staff and get the %text, even if V:2 is not yet fully rendered. The rest of V:2 then comes later.

**Comment by moinejf** [comment]
%%text (as other %% commands) is inserted in the top voice (the first voice in %%score) at its current time. There is no voice synchronization on such commands. Only %%score does a synchronization.
