### ISSUE TITLE
weird case with multiple score statements

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#5]
```abc
X:1
T: weird score
%%score 1
K:F
V:1
c
%%score 2
V:2 
%
C
```

Yields

![screenshot_896](https://user-images.githubusercontent.com/2022976/29083401-e5a0ac72-7c68-11e7-8531-3112d6f55749.jpg)

and a json model where the notes of V2 do not have a midi entry.

It is getting better if I add a Measure bare after the first "c"

I fully admit that this is a weird case, but it happens, and we should provide a helpful feedback.
Dealing with multiple score statements is rocket science. I feel the spec is not very clear and hard to implement.

**Comment by moinejf** [comment]
Bug fixed by commit 22890c3fe74d2b0c59a955f917f2a52433efd88c
