### ISSUE TITLE
more issues wrt linebreak, $ etc.

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#58]
this is a followup to #52 

If you add a $-character to a chord, then we get a crash:

```
X:1
K:C
c"^$"d 
```

![screenshot_1039](https://user-images.githubusercontent.com/2022976/33219285-bb9c6db6-d141-11e7-9c81-cdd9e92707af.jpg)

It appears to me that there is a builtin preset for linebreak to be

```
I:linebreak $ <EOL> 
```
This is a bit confusing because:

* I could not find documentation about this. ABC-Standard does not specify a default. I somehow remember that in earlier versions "$" was flagged as illegal character without linebreak instruction. But I no longer have such an old version. I tried with Zupfnoter 1.0 (using abc2svg 1.2.0) but this already used "$"
* The documentation says that in abc2svg linebreak may have only one argument (http://moinejf.free.fr/abcm2ps-doc/linebreak.xhtml). But the default has $ and <EOL>. If i uncomment the linbreak statement below, it works as expected.

It is not a big deal. I just would like to clarify this.

```abc
X:1
T:handling linebreaks in abc2svg
F:3050_handling-linebreaks-in-abc2-svg
%I:linebreak <EOL>
I:measurenb 1
I:linewarn 0
K:C
V:1
CCCC| CCCC | CCCC | 
"^linebreak by <EOL>" CCCC| CCCC |*  dddd |$ "^linebreak by Dollar" cccc | eeee | CCCC |* CCCC |CCCC| CCCC | CCCC |
%
W:Expected result:
W:.
W:Linebreak should not appear in measure 7 
```
![screenshot_1038](https://user-images.githubusercontent.com/2022976/33218853-7224dc1a-d13f-11e7-8836-b45afc0fdea1.jpg)

**Comment by bwl21** [comment]
It works. Thanks

**Comment by bwl21** [comment]
I reopen it since the issues wrt to line break are not yet handled (I should not have created a ticket with multiple issues)

Do I understand right 
* that abc2svg tries to avoid "line too much shrunk" as far as possible? It even adds additional linebreaks if needed.
* linewarn 0 does not suppress "line too much shrunk"
* "line too much shrunk" can still occur in some circumstances: (e.g. it cannot find a valid break, in particular in multivoice)
* it considers "line underfull"  to be more acceptable than "line too much shrunk"

**Comment by moinejf** [comment]
abc2svg tries to give a good rendering of the music written in ABC. Especially, it adds music line breaks so that there is no clash of the symbols nor symbols out of the page.
The message "line too much shrunk" indicates there is a bug in the music splitting algorithm of abc2svg which gives a bad music rendering. This message cannot be suppressed.
The message "line underfull" indicates there are too few symbols in a music line. This a user decision, and the message may be suppressed by %%linewarn 0.

**Comment by bwl21** [comment]
Does it mean you would like to have reports "about line too much shrunk"? As of now I have four cases with this. Some of the files are from my users, so I cannot post them here. Shall I ask for permission to send it. I then would zip it and send it by PM.

**Comment by moinejf** [comment]
I love small examples. Please, try to reduce the tunes just one step before the bug appears. The exact notes are not important.

**Comment by bwl21** [comment]
Ok, I will take the four files raising "line too much shrunk" and tray to nail it down to shorter examples.

**Comment by bwl21** [comment]
I tested it with testcase 3052, 3053, 3054. There is no more "line too much shrunk" message.

Was this fixed by commit 3c800d4 ?

Was there something specific in the files which caused the message? I could not see any difference in the header compared with the other files.

**Comment by moinejf** [comment]
On Mon, 27 Nov 2017 09:47:56 +0000 (UTC)
Bernhard Weichel <notifications@github.com> wrote:

> Was this fixed by commit 3c800d4 ?

To insert lines breaks, the line splitting function (cut_tune) computes
the whole width of the tunes, and divides this number by the width of a
line.
At the time this function is called, there is no start of staff, i.e.
no clef, no key signature and no time signature (meter). The clef and
time signature exist in each line, so, their width may be substracted
from the available line width. But the meter is put in the first line,
so, its width must be added to the real width of the tune.
This width was forgotten.

-- 
Ken ar c'hentañ	|	      ** Breizh ha Linux atav! **
Jef		|		http://moinejf.free.fr/

**Comment by bwl21** [comment]
I see, but why did it occur only in these three files (out of 650)? 
I am sure, that cut_tune also has to ensure, that it breaks on measure bars if possible. This could lead to a border situation, where it does not break the lines, but still shrinks it too much. Was this the situation?

In particular in case 3052 it could not find a a proper line break. So the last line is cropped). There was not error message either.

if you play around with the rests at end of line 21, you can see various effects. In particular it is still possible to get "line too much shrunk".

To be honest, I don't think it is worth to avoid "line too much shrunk" regardless what it costs. This message indicates that eventually the abc needs to be fixed.

So if the situation is clearly documented, we could live with the current status. It is an exotic case either :-)

```abc
X:3008
F:3052 linewarn
T:linewarn
I:linebreak <EOL> 
M:4/4
L:1/4
Q:1/4=120
K:C
%%score  1 2
V:1 clef=treble name="Sopran" snm="S"
"^!G,,@-2,5" G,, "^!^G,,@-2,5"^G,, "^!A,,@-2,5"A,, "^!^A,,@-2,5"^A,, "^!B,,@-2,5"B,,
%
"^!C,@-2,5"C, "^!C,@-2,5"^C, "^!D,@-2,5"D, "^!^D,@-2,5"^D, "^!E,@-2,5"E, "^!F,@-2,5"F,
"^!^F,@-2,5"^F, "^!G,@-2,5"G, "^!G,@-2,5"^G, "^!A,@-2,5"A, "^!^A,@-2,5"^A, "^!B,@-2,5"B,
%
%
"^!C@-2,5"C "^!C@-2,5"^C "^!D@-2,5"D "^!^D@-2,5"^D "^!E@-2,5"E "^!F@-2,5"F
"^!^F@-2,5"^F "^!G@-2,5"G "^!G@-2,5"^G "^!A@-2,5"A "^!^A@-2,5"^A "^!B@-2,5"B
%
"^!c@-2,5"c "^!c@-2,5"^c "^!d@-2,5"d "^!^d@-2,5"^d "^!d@-2,5"e "^!f@-2,5"f
"^!^f@-2,5"^f "^!g@-2,5"g | z4 |z37 %line 21
%
%%%%%%%%%%%%%%%%%%%
%
V:2 clef=treble octave=-1 name="Sopran" snm="S"
x37 | "^!G,@-2,5" G, "^!^G,@-2,5"^G, "^!A,@-2,5"A, "^!^A,@-2,5"^A, "^!B,@-2,5"B,
%
"^!C@-2,5"C "^!^C@-2,5"^C "^!D@-2,5"D "^!^D@-2,5"^D "^!E@-2,5"E  "^!F@-2,5"F 
"^!^F@-2,5"^F "^!G@-2,5"G "^!G@-2,5"^G "^!A@-2,5"A "^!^A@-2,5"^A "^!B@-2,5"B
%
"^!c@-2,5"c "^!^c@-2,5"^c "^!d@-2,5"d "^!^d@-2,5"^d "^!e@-2,5"e "^!f@-2,5"f 
"^!^f@-2,5"^f "^!g@-2,5"g "^!^g@-2,5"^g "^!a@-2,5"a "^!^a@-2,5"^a "^!b@-2,5"b
%
"^!c'@-2,5"c' "^!c'@-2,5"^c' "^!d@-2,5"d' "^!^d'@-2,5"^d' "^!d@-2,5"e' "^!f@-2,5"f'
"^!^f'@-2,5"^f' "^!g@-2,5"g' |
%
V:3
z37 | z37 | z37 |
```

**Comment by moinejf** [comment]
It occured only in few files because the program had only few bugs :)

The music line cut occurs on a measure bar when possible, or on the beat when possible, or on the exact symbol which creates the line overflow.

I think your 3052 is the tune in the message. Well, there is still a bug in the music line splitting algorithm :(
On explicit line break and no overflow, the line is cut on the next symbol of the current voice without more check. In your tune, the line break is on the last rest of V:1, and, so, the line is cut at the end of its duration, i.e. at the end of V:2.
I have to re-think the algorithm...

**Comment by bwl21** [comment]
> It occured only in few files because the program had only few bugs :)

The purpose of a testsuite is to prove that the software has bugs. But with abc2svg this is a hard job as there are only very few of those. :-)

**Comment by bwl21** [comment]
I verified the testcase 3052 with 1.15.4. I works as expectd. So I close this.
