### ISSUE TITLE
How can I find out why a voice has no symbols

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#6]
# Request
I observe two reasons why the json model contain voices without symbols:

1. the voice is not referenced by the %%score - statement
2. the %%score - statement refers to a non existing voice

Is there a way to distinguish these two cases such that I can provide a proper error message to the user.

# Solution approach

Best would be if 
* abc2svg reports if %%score refers to a non existing voice
* simply ignores (does not reflect in the model) voices which are not referenced by the %%score statement.

**Comment by moinejf** [comment]
I changed json.js by commit d78adabd0795b9c510ae33f0620fe8eb724ebe51 so that the empty voices are not dumped.
Is this OK for you?

**Comment by bwl21** [comment]
Empty voices might be dumped if they are referenced in %%score. Then I can tell the user that he has an empty voice.

They should not be dumped if they are not referenced in the  %%score.

Alternatively if you also find a way to expose the parameters of %%score.  E.g. in the staves symbol. This would allow even to inform user about unreferenced voices.

**Comment by moinejf** [comment]
Well. I will revert the previous commit and put the internal staff system in the STAVES symbol.
The empty voices will always be dumped.
Will that be the right solution for you?

**Comment by bwl21** [comment]
I think it is the most flexible approach. How would you represent in STAVES. Will it be an array of numbers?

**Comment by bwl21** [comment]
I have integrated commit b85eb72 which includes the staves. I am a bit confused how to get the information I need:

1. if there is no %%score - Statement in the ABC i do not get a stave symbol. It would be good, if in thiscase I get the properties of the default (with istart: 0)
2. 

```
X:3043
F:detect-empty-or-unused-voices
T:Detect empty or unused voices
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%%score 1 2
V:1 clef=treble name="Sopran" snm="S"
C  & E |
V:2
V:3
D 
%
W:Expected result:
W:
W:Voice 2 shall be indicated as error: Empty Voice 2
W:Voice 3 shall be indicated as Info: Unused Voice 3
```
gives the json below for the staves symbol. 

* How can I find out that Voice 1 and 2 are referenced while Voice 3 is not referenced?
* Does "voices" reflect to all voices in the the abc?
* How are voice overlays represented?

```JSON
{
  "type": 12,
  "dur": 0,
  "sy": {
    "voices": [
      {
        "range": 0,
        "st": 0,
        "second": null
      },
      {
        "range": 2,
        "st": 1,
        "second": null
      },
      {
        "st": 0,
        "second": true,
        "scale": 1,
        "key": {
          "type": 5,
          "k_delta": 0,
          "dur": 0,
          "ctx": {
            "fname": "abc"
          },
          "istart": 99,
          "iend": 102,
          "k_sf": 0,
          "k_mode": 0
        },
        "ckey": {
          "type": 5,
          "k_delta": 0,
          "dur": 0,
          "ctx": {
            "fname": "abc"
          },
          "istart": 99,
          "iend": 102,
          "k_sf": 0,
          "k_mode": 0
        },
        "okey": {
          "type": 5,
          "k_delta": 0,
          "dur": 0,
          "ctx": {
            "fname": "abc"
          },
          "istart": 99,
          "iend": 102,
          "k_sf": 0,
          "k_mode": 0
        },
        "pos": {
          "dyn": 0,
          "gch": 0,
          "gst": 0,
          "orn": 0,
          "stm": 0,
          "voc": 0,
          "vol": 0
        },
        "range": 1
      },
      {
        "range": -1
      }
    ],
    "staves": [
      {
        "stafflines": "|||||",
        "staffscale": 1,
        "flags": 64
      },
      {
        "stafflines": "|||||",
        "staffscale": 1,
        "flags": 0
      }
    ],
    "top_voice": 0,
    "nstaff": 1
  },
  "ctx": {
    "fname": "abc"
  },
  "istart": 116,
  "iend": 153,
  "v": 0,
  "st": 0,
  "time": 0,
  "pos": {
    "dyn": 0,
    "gch": 0,
    "gst": 0,
    "orn": 0,
    "stm": 0,
    "voc": 0,
    "vol": 0
  }
}
```

**Comment by moinejf** [comment]
On Thu, 10 Aug 2017 15:33:15 +0000 (UTC)
Bernhard Weichel <notifications@github.com> wrote:

> I have integrated commit b85eb72 which includes the staves. I am a bit confused how to get the information I need:
> 
> 1. if there is no %%score - Statement in the ABC i do not get a stave symbol. It would be good, if in thiscase I get the properties of the default (with istart: 0)

OK. I will add a generated STAVES symbol that will have:
- its istart value as the reference of the first symbol of the tune body,
- the property 'default'.

> 2. 
	(snip)
> * How can I find out that Voice 1 and 2 are referenced while Voice 3 is not referenced?

In the 'sy' object of the STAVES symbol, the 'voices' table is indexed
by the voice number. The 'range' indicates the range of the voice in the
%%score. A negative range indicates the voice is not referenced.

In your example, there are 4 voices:
- voice 0: range = 0 (V:1)
- voice 1: range = 2 (V:2)
- voice 2: range = 1 (voice overlay of V:1)
- voice 3: range = (-1) (V:3)

> * Does "voices" reflect to all voices in the the abc?

No. the 'voices' table contains only the voices which were defined in
the %%score plus the voices found in the tune body up to the next
%%score.

> * How are voice overlays represented?

The voice overlays have no special property.
Instead, they are pointed to by their upper voice.

For example:
    c & G & C
gives:
    voice_tb[0].voice_down -> voice_tb[1]
    voice_tb[1].voice_down -> voice_tb[2]
(no pointer in voice_tb[1])

**Comment by moinejf** [comment]
(indeed, the last line of the previous comment is
    no pointer in voice_tb[2]
)

**Comment by bwl21** [comment]
> 
> OK. I will add a generated STAVES symbol that will have:
> - its istart value as the reference of the first symbol of the tune body,
> - the property 'default‘.

fine thanks

> 
> > 2. 
> (snip)
> > * How can I find out that Voice 1 and 2 are referenced while Voice 3 is not referenced?
> 
> In the 'sy' object of the STAVES symbol, the 'voices' table is indexed
> by the voice number. The 'range' indicates the range of the voice in the

Is Voice number the same index as in voices of the main object.
So STAVE.voices correlates to voices on the top level?

In other words. The voices arrays reflect the sequence of the voices referenced in the %%score statement.
Voice overlays appear after the voices referenced in the %%score but before the voices not referenced in the %%score.

Zupfnoter references the voices in its configuration by the index into the „voices“ of the top level music model. 
This is a nice feature since the user can then swap the voiced in harpnotes by %%score statement.

I am afraid this is a bit fragile, if you want to change something there.
Maybe I need to change that and reference voice by their Id in ABC. But I cannot do that since
it is not backwards compatible.

Do you have an advice?

> %%score. A negative range indicates the voice is not referenced.
> 
> In your example, there are 4 voices:
> - voice 0: range = 0 (V:1)
> - voice 1: range = 2 (V:2)
> - voice 2: range = 1 (voice overlay of V:1)
> - voice 3: range = (-1) (V:3)

Is range a kind of priority?

-1: voice is not referenced
otherwise: the sequence in which the voices are rendered?



> 
> > * Does "voices" reflect to all voices in the the abc?
> 
> No. the 'voices' table contains only the voices which were defined in
> the %%score plus the voices found in the tune body up to the next
> %%score.

I got it … in my case voice 3 was not defined in the %%score but
still appears in the voices table of the stave symbol. 
I think this is even necessary 
since the voices table there is indexed and does not reflect the value of 
voiceproperties.id (which btw would be very helpful) for reporting.

Reason vor voice 3 showing up is, that all voices up to the next 
%%score are reflected. Nevertheless I will avoid more than one %%score beyond „default“.

> 
> > * How are voice overlays represented?
> 
> The voice overlays have no special property.
> Instead, they are pointed to by their upper voice.
> 
> For example:
> c & G & C
> gives:
> voice_tb[0].voice_down -> voice_tb[1]
> voice_tb[1].voice_down -> voice_tb[2]
> (no pointer in voice_tb[1])

I see that my implementation for voice overlays is broken, it worked somehow,
but I guess it is not very robust.

I observe that the voice overlays appear twice:

1. in the voice_down
2. in voices - Array of the music model.

Zupfnoter up to now considers voice overlays as an extra voice. 
In Zupfnoter-Configuration, I refer to it by the index for Voices starting with „1",
im my example, the overlay is referenced with index „2“

**Comment by moinejf** [comment]
On Fri, 11 Aug 2017 03:12:22 -0700
Bernhard Weichel <notifications@github.com> wrote:

> > In the 'sy' object of the STAVES symbol, the 'voices' table is indexed
> > by the voice number. The 'range' indicates the range of the voice in the
> 
> Is Voice number the same index as in voices of the main object.
> So STAVE.voices correlates to voices on the top level?
> 
> In other words. The voices arrays reflect the sequence of the voices referenced in the %%score statement.

The voices have a unique index which is used at various places (in the
voices themselves - voice_tb[] -, in the symbols - s.v - ...), and
which is also the index of STAVES.voices[].

> Voice overlays appear after the voices referenced in the %%score but before the voices not referenced in the %%score.

That's not right. The voices (and their index) are created in the order
they are found in the ABC source. In this example

%%score 1 2
V:1
C & c
V:3
V:2
C & c

the voices are:

0: V:1
1: V:2
2: overlay V:1
3: V:3
4: overlay V:2

> Zupfnoter references the voices in its configuration by the index into the „voices“ of the top level music model. 
> This is a nice feature since the user can then swap the voiced in harpnotes by %%score statement.
> 
> I am afraid this is a bit fragile, if you want to change something there.
> Maybe I need to change that and reference voice by their Id in ABC. But I cannot do that since
> it is not backwards compatible.
> 
> Do you have an advice?

Sorry, I already have too much to think about the staves...

> > %%score. A negative range indicates the voice is not referenced.
> > 
> > In your example, there are 4 voices:
> > - voice 0: range = 0 (V:1)
> > - voice 1: range = 2 (V:2)
> > - voice 2: range = 1 (voice overlay of V:1)
> > - voice 3: range = (-1) (V:3)
> 
> Is range a kind of priority?
> 
> -1: voice is not referenced
> otherwise: the sequence in which the voices are rendered?

Right. The range 0 gives the top voice which contains the time. This voice is sometimes named the 'control voice'. Then, in each staff, the voice with the smallest range has its stems upwards.

> > > * Does "voices" reflect to all voices in the the abc?
> > 
> > No. the 'voices' table contains only the voices which were defined in
> > the %%score plus the voices found in the tune body up to the next
> > %%score.
> 
> I got it … in my case voice 3 was not defined in the %%score but
> still appears in the voices table of the stave symbol. 

The 'voices' in the staffsystem (STAVES.sy.voices[]) is updated when
finding an other %%score or at end of tune.
In the example at the top of this message, if we add

%%score 1 4
V:1
C
V:4
C

the first STAVES is unchanged, while the second one contains all the
previous voices plus

5: V:4

> I think this is even necessary 
> since the voices table there is indexed and does not reflect the value of 
> voiceproperties.id (which btw would be very helpful) for reporting.
> 
> Reason vor voice 3 showing up is, that all voices up to the next 
> %%score are reflected. Nevertheless I will avoid more than one %%score beyond „default“.
> 
> > > * How are voice overlays represented?
> > 
> > The voice overlays have no special property.
> > Instead, they are pointed to by their upper voice.
> > 
> > For example:
> > c & G & C
> > gives:
> > voice_tb[0].voice_down -> voice_tb[1]
> > voice_tb[1].voice_down -> voice_tb[2]
> > (no pointer in voice_tb[1])

(no pointer in voice_tb[2])

> I see that my implementation for voice overlays is broken, it worked somehow,
> but I guess it is not very robust.
> 
> I observe that the voice overlays appear twice:
> 
> 1. in the voice_down
> 2. in voices - Array of the music model.

voice_down is a pointer to the voice_tb array.

> Zupfnoter up to now considers voice overlays as an extra voice. 
> In Zupfnoter-Configuration, I refer to it by the index for Voices starting with „1",
> im my example, the overlay is referenced with index „2“

An voice overlay is a normal voice. It just has no specific ID, and,
so, it cannot enter as 'V:something' in the ABC source. But it may have
anything a normal voice can have: scale, staff change, specific
octave/transposition, map...

-- 
Ken ar c'hentañ	|	      ** Breizh ha Linux atav! **
Jef		|		http://moinejf.free.fr/

**Comment by moinejf** [comment]
Error of mine:
When an other %%score is found, the new voices are added in STAVES.sy.voices[],
but before the generation (and get_abcmodel), the voices[] arrays of all %%score are
filled with all voices (and a range = (-1) when missing).
Then, all STAVES.sy.voices[] have the same length.

**Comment by bwl21** [comment]
I see. So in the JSON all STAVES are eventually of the same length, but not of the same content.

I double checked the example you have mentioned before and found it indeed in the json.
This means that the voice indexes remain stable and I can rely on it.

Back to the original question, I summarize:

I can find voices which are not referenced in a %%score by checking its range in the staves symbol.

Thanks. I will try it and close this issue this weekend.

**Comment by bwl21** [comment]
I have implemented the detection of empty voices by checking its range in the (most recent) staves symbol.

I think istart/iend of the staves symbol does not yet reflect the position of %%score.

To report the error, i have still the problem to get the correct position (istart, iend) in the ABC. 

```
 1: X:21
 2: K:C
 3: %%score 1 2 3 4 
 4: V:1
 5: C & c
 6: V:3          % this is empty
 7: V:2
 8: C &         % the voice overlay is empty
 9: V:5
```
Zupfnoter reports (note that V:5 is not reported since it is not in the %%score)
```
Empty voice 3: V:3   - case 1
Empty voice 4: V:4   - case 2
Empty voice 6: V:2o - case 1
```
We have two cases with respect to error position:

1. %%score refers to a voice which is declared but has no elements: V:3, V:2o; error pointer should be in line 6, respectively line 7  - the voice declarations - which is not available yet (Istart/Iend of the voice refers to the key, in this case always line 2).
2. %%score refers to a voice which is not declared: V:4; error pointer should be in line 3 - istart/iend from the score-symbol (which is currently available but with wrong values)

**Comment by moinejf** [comment]
I don't see why you want to detect the empty voices.
Empty voices do exist when extracting, for instance, the alto voice of a
SATB tune or the harp part of a piece for orchestra.

In the model, the source reference is useful when there can be errors
with the symbol after parsing. %%score does not bring such errors, and
also, the source reference of the first %%score has been lost a long
time ago before it is inserted in a voice.

Anyway, why do you want a source pointer while the user can see by
him/herself there is no symbol in such or such voice?

**Comment by bwl21** [comment]
Gooe questions. I try to explain. Somtimes my users miss a voice in the generated harpnotes and ask me why?. I want to help them finding the reason by pointing to the most probable locatinvin Abc.  I therefore wanted to add a link in the message where to fix. Zupfnoter reports in the abc code also problems detected while generating harpnotes.

So if a user refers to a non existing voice in the %score, this voice apprears as empty voice, but the user needs to fix it in the score. Oth if the score refers to a voice which is declared but has no symbols, it needs to be fixed in the voice (V:) not in the score. 

One of the most popular errors are for example are blank lines after a voice declaration.

But i also want to express, that these special cases are not that important to justify big changes in the code now. If you will not provide istart for %%score and V:, let me know and i close the issue. Your representation of score gives allows me to give much better user infirmation than before.

**Comment by moinejf** [comment]
There may be a lot of mistakes in ABC and finding all of them is
impossible.
Mispelled names of parameters, voices... are often seen.
What could you say to a user when (s)he says the score is not correct
and (s)he wrote '%%scores' or '%%tranpose' ?
And what about wrong note durations, lack of measure bars... ?
If you really need it, you should write a tool for ABC as 'lint' for
the C language, and find common errors...

**Comment by bwl21** [comment]
I think it is a very good idea to implement a kind of lint. I will try this based on the json model.

So if I got it right you will keep istart of voices and stave symbols pointing to K: header.  Accepted. Thanks for all help.
