### ISSUE TITLE
unexpected linebreak disappears when I add a manual linebreak

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#63]
```abc
I:measurenb 1
I:staffnonote 2
%I:linebreak $
% --------------
X:1
F:1_3010measurenumber
T:measure-number
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%
%
%%score 1
%
V:1 clef=treble name="Sopran" snm="S"
CCCC | DD::DD |1 EEEE |2 DDED || (3EEEeEE | EEEE
```
Yields

![screenshot_1054](https://user-images.githubusercontent.com/2022976/33527362-8c750952-d84f-11e7-9595-84323c0e70b2.jpg)

but when I add a linebreak in the source before the "|1" 

```abc
% - settings to improve Handling in Zupfnoter
I:measurenb 1
I:staffnonote 2
%I:linebreak $
% --------------
X:1
F:1_3010measurenumber
T:measure-number
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%
%
%%score 1
%
V:1 clef=treble name="Sopran" snm="S"
CCCC | DD::DD 
|1 EEEE |2 DDED || (3EEEeEE | EEEE
```

I get it in one line

![screenshot_1055](https://user-images.githubusercontent.com/2022976/33527379-f8c2b7bc-d84f-11e7-8c96-1296e4e0c01a.jpg)

**Comment by bwl21** [comment]
I could safely reproduce it with 1.15.3. 

I tried again with 1.15.4. Now it works as expected. 
The first example now yields one line. The second example now yields two lines

Maybe it was fixed with #62. I you find this reasonable, we can close this.

**Comment by moinejf** [comment]
Indeed, #62 fixed a lot of bad cases. Anyway, as for #64, the most important is that the problem disappeared.

**Comment by bwl21** [comment]
so I close this as well.
