### ISSUE TITLE
Q: what is the safest way to print text after the staff lines (or how to terminate music properly)

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#65]
I open this ticket for better understanding.

* what is the best way to add a textnote after the music? I want to do this by manipulating the abc code before handing it over to abc2svg
* what is the best way to ensure that the last line spans the page width?

I tried two options:

## Option 1: add the note separated by a blank line

This seems to treat the note as another song. The textnote is added after the lyrics.
In this case the last line does not span the page width because it is underfull.

```
X:1
T:test with text
%%scale 0.83
%%pagewidth 21.00cm
%%leftmargin 1.00cm
%%rightmargin 1.00cm
%%score 4
I:linebreak $
L:1/8
M:3/4
K:C
V:4 bass+8 nm="Bass Recorder, Tenor" snm="B. Rec."
 G,,3 B,, B,,C, | B,,4 z B,, | B,,3 B,, C,B,, | A,,2 G,,2 z G,, |  A,,3 G,, F,,F,, |$
 G,,4 z3 |]$  %33
% 
W:|: lorem ipsum
W:ipsum lorem :|

%%text foo
```
yields

![screenshot_1061](https://user-images.githubusercontent.com/2022976/34036026-3b66d23c-e184-11e7-810d-b2d0bc8c2d10.jpg)

## Option 2: add a line break and the textnote

In this case I declare another linebreak before
* This approach adds the note between the staff and the lyirics (because it is treated as part of V:4 ?)
* the last line spans the page (because the text is the last line?)

```
X:1
T:test with text
%%scale 0.83
%%pagewidth 21.00cm
%%leftmargin 1.00cm
%%rightmargin 1.00cm
%%score 4
I:linebreak $
L:1/8
M:3/4
K:C
V:4 bass+8 nm="Bass Recorder, Tenor" snm="B. Rec."
 G,,3 B,, B,,C, | B,,4 z B,, | B,,3 B,, C,B,, | A,,2 G,,2 z G,, |  A,,3 G,, F,,F,, |$
 G,,4 z3 |]$  %33
% 
W:|: lorem ipsum
W:ipsum lorem :|
I:linebreak $
$
%%text foo
```

![screenshot_1062](https://user-images.githubusercontent.com/2022976/34036075-69a7d15a-e184-11e7-801a-26ce8a4ca639.jpg)

## trying to understand

Is the following conclusion correct?:

* %%text is handled as a symbol of a voide which is rendered after termination of the line
* %%text must immediately follow the linebreak to be rendered
* The last line does not span the page if it is underfull. In the second approach above, the %%text becomes the last line, so the staff is renderd to span the page width.

**Comment by moinejf** [comment]
A ABC tune starts on X: and ends on a blank line. The music starts on the first K: of a tune.
The music is stretched to fill the line according to the option %%stretchstaff.
The last line of the music is stretched according to the option %%stretchlast.

The formatting commands are normally rendered as encountered in the ABC file.
But, when found inside the music, some formatting commands as T:, %%text, %%sep, %%vskip... are inserted as music symbols. These symbols are rendered only when they follow a line break.

Example:
```
X:1
T:tune title
%%text this text is immediately rendered, so, it goes before the tune
%%bgcolor lightblue
M:C
L:1/4
K:C
c4 | [I:text this inline text is ignored] c4|\
%%text and same here (no line break)
c4|
%%text this text is inside the music
c4|]
%%text this text is the last symbol of the tune in a new music line

%%text this text is in a separated block
```
(you may also try this example adding "%%linebreak <none>")

**Comment by bwl21** [comment]
Thanks for the answer. The essential point is "These symbols are rendered only when they follow a line break." As consequence of this i will implement option 2 in zupfnoter.

**Comment by bwl21** [comment]
I See hat Option 2 no longer Works in 1.15.5 because of commit fc3d89e . Anyhow this commit makes the behaviour much clearer.

The intended result (füll width last line) be achieved by setting stretchlast.
