### ISSUE TITLE
Comment on an bar breaks variant ending

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#66]
```
X:11
T:vertal Ent
S:
M:3/4
L:1/4 
Q:1/4=120
K:C
%%score T1
V:T1 clef=treble name="Sopran" snm="S"
C  |1c  c "^foo":|[2 c2  |] D
```

Yields

![screenshot_1069](https://user-images.githubusercontent.com/2022976/34162370-bf98d454-e4d3-11e7-80cd-9afa133b55fe.jpg)

If I change to 

```
C  |1c  c "^foo":|]2 c2  |] D
```

I get

![screenshot_1070](https://user-images.githubusercontent.com/2022976/34162394-d57f702a-e4d3-11e7-9efd-4a0baf76ed4b.jpg)

The difference is that also the rbstart/rbstop is different. Admittedly this is again an exotic issue, but it might be an issue ...

**Comment by moinejf** [comment]
Yes, that was a bug. Thanks.

**Comment by bwl21** [comment]
Checked with 1.15.5
