### ISSUE TITLE
Style problems when rendering multiple SVG

### ISSUE THREAD

**Issue by tlarrain** [moinejf/abc2svg#68]
I have a project in Ionic and it have a view with an ion-slides inside. Every slide contains a different SVG image rendered with this library. The problem is that the inline style tag have the same style names and it overrides each other, having problems with the same parts of different images
<img width="1047" alt="screen shot 2017-12-29 at 17 00 53" src="https://user-images.githubusercontent.com/7906220/34446456-e396794a-ecb9-11e7-97d1-2817908e293f.png">
<img width="1043" alt="screen shot 2017-12-29 at 17 01 08" src="https://user-images.githubusercontent.com/7906220/34446457-e3b827c0-ecb9-11e7-928a-40cda5f90b43.png">

**Comment by moinejf** [comment]
I don't fully understand what you are doing, but you can set different style names using

```
%%fullsvg x
```

'x' is a suffix which is added to the class defining the fonts.
Each tune/generation set may have a different suffix.
(see http://moinejf.free.fr/abcm2ps-doc/fullsvg.xhtml)

**Comment by tlarrain** [comment]
That should do the trick, thank you very much!
