### ISSUE TITLE
GainNode.gain.value setter smoothing is deprecated

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#69]
# Request

After upgrading Chrome to Version 63.0.3239.108 (Offizieller Build) (64-Bit)
I get the following message in Chrome console on http://moinejf.free.fr/js/edit-1.xhtml

![screenshot_1085](https://user-images.githubusercontent.com/2022976/34453767-a8cd275c-ed5c-11e7-9ecb-d5206ab7f47d.jpg)

play-1.js:5 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
Audio5 @ play-1.js:5

**Comment by moinejf** [comment]
Sorry for I cannot find the subject you are talking about in the huge chromestatus document.

**Comment by bwl21** [comment]
https://github.com/photonstorm/phaser-ce/issues/385 provides a solution for the issue

The link leads to 

![screenshot_1086](https://user-images.githubusercontent.com/2022976/34453791-fd9e9752-ed5c-11e7-870f-a40664f0522a.jpg)

**Comment by moinejf** [comment]
Sorry again, I don't see how I am impacted..

**Comment by bwl21** [comment]
I have done the necessary changes on my fork and created a pull request

**Comment by moinejf** [comment]
I still don't see why setting the gain as it is actually should be changed:
https:developer.mozilla.org/en-US/docs/Web/API/GainNode/gain

**Comment by bwl21** [comment]
We will see if abc2svg play stops working on the next version of Chrome. You might be right, that the change is not necessary if we do not need "smoothing" of gain changes.

I propose to leave the issue open and see what happens with Chrome 64.

**Comment by moinejf** [comment]
As I understood, when setting the gain, chrome did a special treatment (smoothing) that does not exist in other browsers. Removing this treatment just makes chrome to work in a more standard way.

**Comment by bwl21** [comment]
I think we close this. I now have chrome 64. It still works, even if the  deprecation messages is still there. 

But now there is another one telling that by M65 in March behavior will change. But as you said, useage by Abc2svg is not affected. So there is no reason to keep this issue open.

play-1.js:5 [Deprecation] GainNode.gain.value setter smoothing is deprecated and will be removed in M64, around January 2018. Please use setTargetAtTime() instead if smoothing is needed. See https://www.chromestatus.com/features/5287995770929152 for more details.
Audio5 @ play-1.js:5
play-1.js:5 [Deprecation] AudioParam value setter will become equivalent to AudioParam.setValueAtTime() in M65, around March 2018  See https://webaudio.github.io/web-audio-api/#dom-audioparam-value for more details.
Audio5 @ play-1.js:5

**Comment by ListeH** [comment]
so when I have these two warnings its okay?

**Comment by moinejf** [comment]
Yes. I have the same warnings with Vivaldi, but everything is fine.
I hope these warnings to disappear in March.

**Comment by bwl21** [comment]
I hope so too. I think they need to remove the warnings, since the code is still ok, only some behavior changes (and abc2svg does not rely on this behavior).

**Comment by bwl21** [comment]
These warnings no longer appear. I guess due to the rework of the player in 1.16

**Comment by moinejf** [comment]
No. I still have the same warnings in Vivaldi (chrome 64.0.3282.189).

**Comment by bwl21** [comment]
Yes, I have them back again ...

May be it is worth to fix them

**Comment by moinejf** [comment]
Fixing the code would not make the code cleaner: this is a problem with chrome only.
Also, the warnings appear in the javascript console. I don't think people open this console when surfing: they would see a lot of critical bugs in many sites!

**Comment by bwl21** [comment]
of course it is up to you to fix it. Even if anyone produces pages with warnings, it does not mean that I do it as long as I can avoid. But I agree it is not easy (even Zupfnoter throws a warning yet ... )

I'll keep it open for a while to see if the warnings disappear.

**Comment by bwl21** [comment]
Even after some updates it appears that chromium will not remove the deprecation messages.
As the effort is low, I still propose to to fix it. If something goes wrong on a website I always first look into the console. As abc2svg is integrated in other apps, those developers might be irritated by the deprecation messages (as I was).

**Comment by moinejf** [comment]
See
``` https://chromium.googlesource.com/chromium/src/+/b9b924b4656a95b54f2a1182cb5386b6b7d089c8^!/#F2
```

**Comment by bwl21** [comment]
Ok we wait ...

**Comment by bwl21** [comment]
Now with Chrome 66 I do not observe these deprecation messages.
