### ISSUE TITLE
tuplets and bar numbers may look strange

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#7]
This abc 
``` abc
X:1025
F:1025_Tuplet-patterns
T:Tuplet-patterns
C:
S:
I:measurenb 1
M:3/4
L:1/4
Q:1/4=120
U: l="^<"
U: r="^>"
K:C
%%score 1 2 
V:1 clef=treble name="Sopran" snm="S"
[r:c1](3CCC z| (3CCC z | [r:tpl1] (2CD  |  (3:2:2 C2C z | (3"^!xx" [r:tpl3]CEG z |  
[r:tpl4](3 GEC rz | (3 CGC z | (3 CA,C z | [r:tpl5](3 CGF z |  [r:tpl2](3 FGC z |
V:2 octave=-1
GGG |GGG |GGG |GGG |GGG |GGG |GGG |GGG |GGG |GGG |
```
Yields

![screenshot_897](https://user-images.githubusercontent.com/2022976/29108017-5b49dfce-7cdd-11e7-99aa-a40ded67a566.jpg)

maybe it is possible to improve behavior on bar 5, 6, 10

**Comment by moinejf** [comment]
The commit 56c9b2336aa4ed25a3f0c497275a9e0a36b604ee should give better patterns.

**Comment by bwl21** [comment]
Yes it does:

![screenshot_898](https://user-images.githubusercontent.com/2022976/29116545-6580ae64-7cfb-11e7-9736-99c095400153.jpg)

**Comment by bwl21** [comment]
I looked on it again and think it is very good as it is. Thank you
