### ISSUE TITLE
Player does not work on Safari

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#71]
# Problem

The player does not work on safari. I tried to track it down and found that decodeAudiData calls the error callback but does not even provide an error message

I tried with https://mdn.github.io/webaudio-examples/decode-audio-data/ which does not work either (filed a report: https://github.com/mdn/webaudio-examples/issues/5)

# Solution approach

1. announce lack of Safari support
2. implement a fallback with oscillator sounds instead of sampled sound

**Comment by moinejf** [comment]
Safari is not a browser from Mozzilla.
I have no Apple machine, but Safari is based on Webkit. The webkit browsers I know use gstreamer for Audio. Did you check the presence of gstreamer in your system?
If yes, is simple audio streaming (anything.mp3) working?

**Comment by bwl21** [comment]
I filed the report on mdn  as now the mdn documentation is maintained by Microsoft, Apple, Google etc. These pages state that it should work on Safari. I also filed a bug report to Apple.

Even if I am a mac user, I do not regularly use Safari.

So eventually I propose that you state it somewhere in the documentatoin (e.g. in readme.md) that Safari does not play back and close this issue.

**Comment by moinejf** [comment]
Sorry, for I will not do that: there are a lot of browsers that do not handle correctly such or such HTML5 standard feature, and I don't have time nor money enough to test all browsers in all machines with all their possible systems.

**Comment by bwl21** [comment]
Ok, so we keep this issue as a hint in case someone else stumbles in that problem. 

I now reaise a warning in Zupfnoter if someone uses safari.
