### ISSUE TITLE
Provide a fallback for sampled sounds: play with oscillator

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#72]
# Request

could we have a fallback to oscillator sounds (not using samples), because

* we sometimes have problems running the sampled sounds (#71). 
* When using on slow network connection, downloading the samples might take long. 
* For trivial applications, an oscillator sound might be enough

# proposal

control by soundfont type "osc"
provide the timbre as another property in the configuration object

**Comment by moinejf** [comment]
I already removed this feature which does not work fine in FireFox.
If you need it, you may code it yourself replacing toaudio5.js.

**Comment by bwl21** [comment]
Firefox Quantum is a vast improvement. It now plays the oscillator sounds very well. And some of my users complained about the sampled sounds ...

I would not replace toaudio5.js but implement an additional class which I could select in AbcPlay to implement the fallback.

Do you still have the code which you removed before?

**Comment by bwl21** [comment]
Not sure If I still need this as the player is getting better with 1.16 ...

But If, wouldn't it be sufficient to replace load_res() and note_run() accordingly?

**Comment by bwl21** [comment]
My intention was, to use as much as possible from toaudio5 (in particular the timing) but use an osscilaator instead of a soundfont. But as I said, the player is getting better with 1.16, so i close this ticket for the time being.
