### ISSUE TITLE
testcase 1025 position of tuplet bracket

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#76]
Here i see a difference in the position of the tuplet bracket. I feel the changed one is now to close to the stave

```
X:1025
F:1025_Tuplet-patterns
T:Tuplet-patterns
C:
S:
M:3/4
L:1/4
Q:1/4=120
U: l="^<"
U: r="^>"
K:C
%%score 1 2 
V:1 clef=treble name="Sopran" snm="S"
[r:c1](3CCC z (3CCC  | [r:tpl1] (2CD  |  (3:2:2 C2C z | (3"^!xx" [r:tpl3]CEG lz z | 
[r:tpl4](3 GEC rz | (3 CGC z | (3 CA,C z | [r:tpl5](3 CGF z |  [r:tpl2](3 FGC z |
V:2 octave=-1
GGG |GGG |GGG |GGG |GGG |GGG |GGG |GGG 
```

![screenshot_1103](https://user-images.githubusercontent.com/2022976/35184723-8385add6-fdf9-11e7-9546-1517944390e9.jpg)

**Comment by moinejf** [comment]
The difference is due to the same problem of the horizontal resolution of the clash array: the measure bars are a bit higher than the staff, and the tuplet brackets are close to the bar. Then some brackets may be a bit higher.

**Comment by bwl21** [comment]
I see. Currently I am in a similar problem of implementing a crash detection. And I know it is indeed difficult.

I guess you will not to try to improve this, right? In particular we already had such a position e.g. in the second tuplet. -> I close it.
