### ISSUE TITLE
With two staffs, staff lines on the second are shorted if I set '%%pagescale 1.5' in the first one

### ISSUE THREAD

**Issue by rigobauer** [moinejf/abc2svg#77]
I'm creating a react component (react-abc2svg) that uses abc2svg to render music notation. Inside of the component I import Abc...

`import { Abc } from 'abc2svg/abc2svg-1.js'`

... and to create the svg I follow this procedure...

```js
class Abc2svgCallbacks {
  constructor() {
    this.abc_svg_output = ""
    this.abc_error_output = ""
    this.img_out = (data) => { this.abc_svg_output += data; }
    this.errmsg = (msg, ln, cn) => { this.abc_error_output += msg + "<br/>\n"; }
    this.read_file = (fn) => ""
    this.anno_start = (music_type, start_offset, stop_offset, x, y, w, h) => {}
    this.anno_stop = (music_type, start_offset, stop_offset, x, y, w, h) => {}
    this.get_abcmodel = (tsfirst, voice_tb, music_types, info) => {}
    this.page_format = true
  }
}

abcCallbacks = new Abc2svgCallbacks()
let abc = new Abc(abcCallbacks)
abcCallbacks.abc_svg_output = ''
abcCallbacks.abc_error_output = ''
abc.tosvg('ABC NOTATION', myAbcNotation)
```

So I get the svg created in abcCallbacks.abc_svg_output, and I can put that inside of a div. I know is not pretty, but is the only way I've found to do it (at least for now).

It works and renders the music, but I've found a problem when I put two components in the same page and change the `pagescale`. For example, just repeating the same notation...

```
// In the first component
%%pagescale 1.5
X:1
T:Test
M:4/4
K:C
|:GcAB dedB|dedB dedB|c2ec B2dB|c2A2 A2BA|


// In the second component
X:1
T:Test
M:4/4
K:C
|:GcAB dedB|dedB dedB|c2ec B2dB|c2A2 A2BA|
```

The result I get is this...

![captura de pantalla 2018-01-22 a las 17 16 39](https://user-images.githubusercontent.com/29883162/35231076-1d40c54c-ff98-11e7-91d1-e92149d6edba.png)

As you can see, the staff lines width of the second component are wrong. If instead of increasing the scale of the first element, I decrease it (`%%pagescale 0.75`), I get this...

![captura de pantalla 2018-01-22 a las 17 21 14](https://user-images.githubusercontent.com/29883162/35231294-b2e913d8-ff98-11e7-9418-79268acced7e.png)

As you can see, then the second staff line width are bigger than they should.

It's like the value of `pagescale` I set in the first component is affecting to the second, but I create new objects on each one, so I don't see why this is happening. I've try all staff related parameters, to see if they have any influence on this, but without success. If also tried to set `%%pagescale 1` on the second one, but it doesn't work. If I have the same `pagescale` on all components, everything works fine.

Any idea of where this can come from?

**Comment by moinejf** [comment]
This is due to the cache of the staff: the definition of the default staff was the same in all runs.
I uploaded a fix for that, but you will have to define a different value in ```%%fullsvg``` each time you create a new Abc instance.
(I have not such a problem in abcemb.js because I use only one Abc instance for the whole document)

**Comment by rigobauer** [comment]
Awesome!! The fullsvg thing is not a problem, I'll make the component create a unique value automatically, so the user won't have to worry about it.
Thank you!
