### ISSUE TITLE
note too close to clef

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#80]
the following testcase

```
X:1
K:C
C C C C
```

Yields  in 1.15.9

![screenshot_1109](https://user-images.githubusercontent.com/2022976/35579158-4aa52d94-05e6-11e8-9ee3-dbab5bcd8973.jpg)

you see that the note is pretty close to clef. If there is only one note, then the distance is the same as in 1.15.8. There I get

![screenshot_1110](https://user-images.githubusercontent.com/2022976/35579177-5522edec-05e6-11e8-90cb-f8e1389b6f7d.jpg)

**Comment by moinejf** [comment]
Sorry for the text of the commit. It should be 'bad X offset of first notes of the staves'.
Thanks for the report.

**Comment by bwl21** [comment]
verified with abc2svg-1.15.9-9-gd0df1a8
