### ISSUE TITLE
how to express alternating measures

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#81]
I have a chorale with alternating measures:

![image](https://user-images.githubusercontent.com/2022976/36538396-917574b4-17d3-11e8-835a-5c8a6608d6b8.png)

I tried `M:2/2 3/2` but then i do not get barnumbers correct

![screenshot_1123](https://user-images.githubusercontent.com/2022976/36538433-bfbedd2e-17d3-11e8-9036-e6cdca917b93.jpg)

with `M:2/2 (3/2)` I get barnumbers but I do not know why and do not like the alternate measure in paranthesis either

![screenshot_1126](https://user-images.githubusercontent.com/2022976/36538512-175390a2-17d4-11e8-8088-39a60721c445.jpg)

http://abcnotation.com/wiki/abc:standard:v2.2#mmeter does not say much about this situation.

**Comment by moinejf** [comment]
With abc2svg/abcm2ps, the measure numbers are printed when the time of the measure bars is greater than the time of the previous bar plus the duration of a measure.
This asks for the program to know the duration of a measures. This is easy for ordinary meters, but, for complex meters, the syntax may be ambiguous.
To solve this problem, abc2svg and abcm2ps accept a simple measure definition in M: after an equal sign. Example:
````
X:1
M:2/4 3/4=5/4
L:1/4
%%measurenb 1
K:C
CD|E2F|\    
GA|B2C|\
D2|cBA|\ 
GF|EDC|]
````

**Comment by bwl21** [comment]
I see. I need to  specify the measure length accoding to the shortest measure

Thanks.
