### ISSUE TITLE
vmap is not defined

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#83]
Trying the following code in edit.xhtml with with commit 93f928dae204a2ca1e8f8c3a7f7e414f6ea78a3e

```abc
X:1
F:1_test-vmap
T:test vmap
C:
S:
M:4/4
L:1/4
Q:1/4=120
K:C
%
%
%%score 1 
%
V:1 clef=treble name="Sopran" snm="S"
c |: c4 :|
```
hit the play button results in 

```
vmap is not defined
abc2svg tosvg bug - stack:
add@http://localhost:63342/abc2svg/play-1.js:382:7
edit_init/user.get_abcmodel@http://localhost:63342/abc2svg/edit-1.js:1:10773
generate@http://localhost:63342/abc2svg/abc2svg-1.js:18564:3
end_tune@http://localhost:63342/abc2svg/abc2svg-1.js:7332:3
tosvg@http://localhost:63342/abc2svg/abc2svg-1.js:7716:3
play_tune@http://localhost:63342/abc2svg/edit-1.js:1:8757
```

**Comment by moinejf** [comment]
As the comment of the commit 6fc2abb says: "this raises a compatibility problem".
The soundfonts are no more in 'FluidR3_GM'. They are in 'Scc1t2' with one JS file per instrument (each file contains a base64 encoded SF2 - Scc1t2/0.js is the acoustic_grand_piano alone).
You have to change the base directory.

About loadjs, this function works only in a web browser context, as toaudio5, and it is used to load any kind of javascript (modules). The equivalent function for a batch context is loadRelativeToScript.
I don't want to put these fonctions into the core, but you may do it.

**Comment by bwl21** [comment]
I think, we are a bit off topic now ...

I managed to get the player work somehow. 

1. I had to adjust jsdir just to be '' (empty string). jsdir tries to find the path to a js folder. In Zupfnoter I have ace.js and dropbox etc. loaded from various folders, even from various servers. So the current definition of jsdir might reveal whatever directory, but not the root of the application.
2. I defined loadjs within zupfnoter.  

   Would it be possible to put these functions in a common module (or even toaudio.js). It appears to me that in needs to be defined in the global namespace.

   Of course it could also be an approach that an embedding application needs to provide this function. Is it used for anything else than loading soundfonts? I no, It could even be defined in toaudio.js.

3. The sound does no longer fade in non loop instruments (it sounds like an organ, even with sound instr. 25 (steel guitar). is it a result of commit 0fc096d2e9da068a83ed1bed07b250f7933faf86

**Comment by moinejf** [comment]
1. jsdir has to be defined in the script from which all the abc2svg specific js files will be loaded.

2. loadjs is used for the soundfonts and the language texts, and also for the modules (actually, capo, diag, grid and psvg).   
  I planned to move some seldom features, as %%MIDI, to modules in the future.

3. The SF2 spec is not clear about sustain/fading. When I will have some time, I will have a look at the source of fluidsynth.

4. The parameters of the editor are stored in cookies.   
  If you changed the soundfont path from the editor, playing will not work until you set it to 'Scc1t2'.
  You may force the path with set_sfu() (set_sft() is now an empty function in play.js).   
  Otherwise, to delete a cookie, set its expiration time to now (see util/toaudio5.js).

**Comment by moinejf** [comment]
Back on 3.
I could not find more information about fading after looking at the source of fluidsynth.
Anyway, I compared playing a steel guitar (25) with swami and with the editor (in Vivaldi). For me, they sound the same: the sound becomes inaudible after about 6s.
Which browser do you use?

**Comment by bwl21** [comment]
Did I get it right that the cookie is related to editor.xhtml only?

as the original issue is solved (vmap not being defined) I opened two followups for the other issues.

**Comment by moinejf** [comment]
The cookie may be set from the 'preferences' of the editor.
Otherwise, it is set by a function and used in toaudio5.js.

**Comment by bwl21** [comment]
Does it mean I have to deal with this cookie in Zupfnoter as well? 


As of now, Zupfnoter does not set cookies. I am using localstorage if i want to save something.

I double checked, and see that there are a bunch of cookies. Do we really need these? I feel, persisting parameters and settings should be a matter of applications like edit-1.xhtml but not of the abc2svg and its components.

I think we should open another issue for further  discussion .. ok?

**Comment by moinejf** [comment]
In toaudio5, the cookies permit to use previously defined play parameters. They are easier to handle than localstorage. The cookies are only:

- sfu: soundfont URL
- follow: follow the music or not
- volume: sound volume

The soundfont URL should not move. Its setting is interesting for development or tests. I don't think that normal users would change it.

The 'follow' flag is used in the editor only for loading the 'follow' script. It is automatically set when this script is loaded by some other means.

The volume depends on the browser and the user audio parameters. I was thinking that this setting could be used when playing static tunes of web pages (i.e. by abcemb.js).
