### ISSUE TITLE
How to show a bar number on the 1st bar of each line

### ISSUE THREAD

**Issue by joaocc** [moinejf/abc2svg#9]
Not sure if this is something that can be enabled in ABC...
What we are looking to show the numbering of the 1st bar of each line.
Thx

**Comment by Badim150** [comment]
Example:
![image](https://user-images.githubusercontent.com/8185565/29180041-5a9f37b0-7dee-11e7-90d8-c2ec8712efa9.png)

**Comment by moinejf** [comment]
See http://moinejf.free.fr/abcm2ps-doc/measurenb.xhtml

**Comment by joaocc** [comment]
Great. Thx!
