### ISSUE TITLE
%%clip stops if measure-number is > 9

### ISSUE THREAD

**Issue by bwl21** [moinejf/abc2svg#94]
I played around with %%clip. It stops working if the symbol selector is > 9

```
I:measurenb 1
%%tune 1
% up to the bar starting the measure #3
%%clip 2-10
%%tune end
X:1
M:C
L:1/4
K:C
CDEF | GABc | CDEF | GABc |CDEF | GABc | CDEF | GABc |CDEF | GABc | CDEF | GABc |
```

doses not yield any tune. It gives error messages `%%tune not treated yet`

I do not yet use this in my app but I plan to add a similar feature (see https://github.com/bwl21/zupfnoter/issues/64)

**Comment by bwl21** [comment]
with 533db89 it only gives message:
```
noname.abc:2:1 Error: %%tune not treated yet
noname.abc:5:1 Error: %%tune not treated yet
```

but id does not yield any notes.

**Comment by moinejf** [comment]
Sorry, I forgot to update the documentation: %%clip works with %%tune only in abcm2ps.
In abc2svg, %%clip works everywhere and %%tune is not handled yet.

**Comment by bwl21** [comment]
I see. I played around and I saw that I could make my app to convert a clip to harpnotes by

```
      abc.tosvg("getmodel","I:clip 2-4");
      abc.tosvg("abc", abc_code);
```

This is great and helps me a lot. Thanks.
