### ISSUE TITLE
Missing diagrams when using %%chordnames

### ISSUE THREAD

**Issue by sonovice** [moinejf/abc2svg#95]
When using `diagram` in conjunction with`chordnames`, diagrams for chords that no longer use common english notation are not shown.

```
X:1
%%chordnames C,D,E,F,G,A,H % German
%%diagram 1
K:C
V:1 treble
"C"C "D"D "E"E "F"F "G"G "A"A "B"B "C"c
```
![unbenannt](https://user-images.githubusercontent.com/8217108/38779828-1bdf2c30-40ce-11e8-8941-781ddee9c21a.PNG)

**Comment by moinejf** [comment]
This bug was fixed a long time ago, but I forgot to fully update the editor of my site.
It should work now. Thanks.
